<a href="https://colab.research.google.com/github/Rizkiramdani04/Portofolio_DS_DA/blob/main/Text_Emotion_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import keras
import tensorflow
# Instead of importing from keras.preprocessing.text, import from tensorflow.keras.preprocessing.text
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Embedding, Flatten, Dense

In [ ]:
dataset=pd.read_csv('/content/trainn.txt',sep=';')
dataset.columns=['Text','Emotions']
dataset.head()

Text Emotions
0  i can go from feeling so hopeless to so damned...  sadness
1   im grabbing a minute to post i feel greedy wrong    anger
2  i am ever feeling nostalgic about the fireplac...     love
3                               i am feeling grouchy    anger
4  ive been feeling a little burdened lately wasn...  sadness

In [ ]:
texts=dataset['Text'].tolist()
labels=dataset['Emotions'].tolist()
tokenizer=Tokenizer()
tokenizer.fit_on_texts(texts)

In [ ]:
sequences=tokenizer.texts_to_sequences(texts)
max_length=max([len(seq) for seq in sequences])
padded_sequences=pad_sequences(sequences,maxlen=max_length)
sequences=tokenizer.texts_to_sequences(texts)

In [ ]:
padded_sequences

array([[   0,    0,    0, ...,    3,   21, 1254],
       [   0,    0,    0, ...,    2,  494,  437],
       [   0,    0,    0, ...,   29,    5, 3496],
       ...,
       [   0,    0,    0, ...,    3,  101, 1331],
       [   0,    0,    0, ...,  339,    8,   42],
       [   0,    0,    0, ...,   25, 3585,   12]], dtype=int32)

In [ ]:
label_encoder=LabelEncoder()
labels=label_encoder.fit_transform(labels)
one_hot_labels=keras.utils.to_categorical(labels)

In [ ]:
one_hot_labels

array([[0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(padded_sequences,one_hot_labels,test_size=0.2,random_state=42)
one_hot_labels[0]

array([0., 0., 0., 0., 1., 0.])

In [ ]:
model=Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index)+1,
                    output_dim=128,input_length=max_length))
model.add(Flatten())
model.add(Dense(units=128,activation='relu'))
model.add(Dense(units=len(one_hot_labels[0]),activation='softmax'))
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(X_train,Y_train,epochs=20,batch_size=32,validation_data=(X_test,Y_test))

Epoch 1/20


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


400/400 ━━━━━━━━━━━━━━━━━━━━ 16s 37ms/step - accuracy: 0.3862 - loss: 1.5317 - val_accuracy: 0.7191 - val_loss: 0.8434
Epoch 2/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 21s 38ms/step - accuracy: 0.8684 - loss: 0.4291 - val_accuracy: 0.8200 - val_loss: 0.5503
Epoch 3/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 15s 37ms/step - accuracy: 0.9823 - loss: 0.0670 - val_accuracy: 0.8259 - val_loss: 0.5680
Epoch 4/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 14s 35ms/step - accuracy: 0.9947 - loss: 0.0234 - val_accuracy: 0.8241 - val_loss: 0.6141
Epoch 5/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9965 - loss: 0.0162 - val_accuracy: 0.8216 - val_loss: 0.6174
Epoch 6/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 16s 39ms/step - accuracy: 0.9969 - loss: 0.0146 - val_accuracy: 0.8147 - val_loss: 0.6775
Epoch 7/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 15s 36ms/step - accuracy: 0.9973 - loss: 0.0110 - val_accuracy: 0.8213 - val_loss: 0.6678
Epoch 8/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 14s 35ms/step - accuracy: 0.9973 - loss: 0.0107 - val_accurac

In [ ]:
input_text = "i am ever feeling nostalgic about the fireplace i will know that it is still on the property"

# Preprocess the input text
input_sequence = tokenizer.texts_to_sequences([input_text])
padded_input_sequence = pad_sequences(input_sequence, maxlen=max_length)
prediction = model.predict(padded_input_sequence)
predicted_label = label_encoder.inverse_transform([np.argmax(prediction[0])])
print(predicted_label[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
love
